use joyaldatabase
select*from[dbo].[Customer]
select*from[dbo].[Transactions]
select*from [dbo].[prod_cat_info]
select top 1*from[dbo].[Customer]
select top 1*from[dbo].[Transactions]
select top 1*from [dbo].[prod_cat_info]

--1)Total number of rows in each of the 3 tables
select count(*) as [count] from[dbo].[Customer] 
select count(*) as [count] from [dbo].[prod_cat_info]
select count(*) as [count] from [dbo].[Transactions]

--2 Total number of transaction with return
select count(distinct(transaction_id)) as [count] from Transactions
where total_amt<0

--3 convert date to valid dates
select CONVERT(date,tran_date,105) as [trans_Date] 
from Transactions
select CONVERT(date,DOB,105) as [DoB]
from Customer

--4 what is the time range of transaction data. Show output in number of days months and years simultaneously in different columns
select DATEDIFF(year,min(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) as Year_dif ,
 DATEDIFF(month,min(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) as Month_dif,
DATEDIFF(DAY,min(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) as day_dif
from Transactions

--5 which product category does subcategory DIY belong to?
select prod_cat,prod_subcat from [dbo].[prod_cat_info]
where prod_subcat='DIY'

--DATA ANALYSIS

select top 1*from[dbo].[Customer]
select top 1*from[dbo].[Transactions]
select top 1*from [dbo].[prod_cat_info]

--1 Most used channel for transaction
Select top 1 Store_type,COUNT(*) as[Count] from Transactions
group by Store_type
order by [Count] desc

--2 Count of male and Female Customers
select Gender ,COUNT(*) as [count] from Customer
where Gender is not null
group by Gender

--3 city with maximum customers and number
SELECT top 1 city_code, COUNT(*) mycount
    FROM Customer
    GROUP BY city_code
	order by mycount desc

--4 Number of subcategories under book category

select prod_subcat as book_subcat  from [dbo].[prod_cat_info] 
where prod_cat='Books'

--5 Max Quantity of Products ordered
select prod_cat_code,MAX(case when Qty>0 then Qty end) as Max_Order
From Transactions
group by prod_cat_code

--6 Net Total revenue generated in categories electronics and books
select sum(cast(total_amt as float)) as Total_revenue from [dbo].[prod_cat_info] as p
inner join Transactions as t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
where prod_cat in('Electronics','Books')

--7 Customers with greater than 10 transactions excluding returns
select count(*) as Num_customer from(
select cust_id,count(distinct(transaction_id)) as tn_cnt from Transactions
where Qty>0
group by cust_id
having count(distinct(transaction_id)) >10) as Table3

 --8 Combined revenue from electronic and clothing categories from flagship stores

select sum(cast(total_amt as float)) as Total_revenue from [dbo].[prod_cat_info] as p
inner join Transactions as t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
where prod_cat in('clothing','Electronics') AND Store_type='Flagship store' AND Qty>0

 --9 Total revenue generated by Male customers in electronics category displayed by prod-sub-category
 select prod_subcat , sum(cast(total_amt as float)) as TL_revenue from Customer as c
 inner join Transactions as t
 on c.customer_Id=t.cust_id
 inner join prod_cat_info as p
 on t.prod_cat_code=p.prod_cat_code AND t.prod_subcat_code=p.prod_sub_cat_code
 where Gender='M' and prod_cat='Electronics'
 Group by prod_subcat

  --10 Percentage of sales by product sub category. Display only top 5 sub categories in terms of sale
 select t1.prod_subcat,Percentage_sales,Percentage_returns from(
select top 5 prod_subcat,SUM(cast(total_amt as float))/(select SUM(cast(total_amt as float)) from transactions where Qty>0) as Percentage_sales from prod_cat_info as p
inner join Transactions as t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
where Qty>0
group by prod_subcat
order by Percentage_sales desc ) as t1
Left Join
--Percentage of return by product sub category
(
select prod_subcat,SUM(cast(total_amt as float))/(select SUM(cast(total_amt as float)) from transactions where Qty<0) as Percentage_returns from prod_cat_info as p
inner join Transactions as t
on p.prod_cat_code=t.prod_cat_code AND p.prod_sub_cat_code=t.prod_subcat_code
where Qty<0
group by prod_subcat) as t2
on t1.prod_subcat=t2.prod_subcat

/*select top 1*from[dbo].[Customer]
select top 1*from[dbo].[Transactions]
select top 1*from [dbo].[prod_cat_info]*/


--11 net total revenue generated by customers between 25 and 35 in last 30 days from max transaction date

select*from(
select * from(select cust_id,datediff(year,dob,max_date) as age,revenue from(
select cust_id,dob,max(convert(date,tran_date,105))as max_date,SUM(cast(total_amt as float)) as revenue from Customer as t1
join Transactions as t2
on t1.customer_Id=t2.cust_id
where Qty>0
group by cust_id,DOB
) as A 
      ) as B
	  where age between 25 and 35)as C

	  join(
select cust_id,convert(date,tran_date,105) as tran_date
from Transactions
group by cust_id,CONVERT (date,tran_date,105)
having convert(date,tran_date,105)>=(select dateadd(DAY, -30,max (convert(date,tran_date,105))) as cutoff_date from Transactions))
as D
on c.cust_id=d.cust_id

--12 product category with max return in last 3 months of transactions
select Top 1 prod_cat_code, sum(Returns) as Tl_returns from	
(select prod_cat_code,convert(date,tran_date,105) as tran_date, SUM (CAST(Qty as int)) As Returns from transactions
where Qty<0
group by prod_cat_code,CONVERT (date,tran_date,105)
having convert(date,tran_date,105)>=(select dateadd(MONTH, -3,max (convert(date,tran_date,105))) as cutoff_date from Transactions)) as A
group by prod_cat_code
order by Tl_returns asc

--13 Store which sells max products by sales and Qty
 select top 1 store_type,SUM(cast(total_amt as float)) as revenue, SUM(cast(Qty as int))as Qty from Transactions
 where Qty>0
 group by Store_type
 order by revenue desc

 --14 Categories where average revenue is greater than overall average
 select prod_cat_code,AVG(cast(total_amt as float)) as avg_revenue from Transactions
 where Qty>0
 group by prod_cat_code
 having AVG(cast(total_amt as float)) >= (select AVG(cast(total_amt as float)) from Transactions where Qty>0)

 --15 Find avg and total revenue by each subcategory for the top 5 categories
 select prod_subcat_code,sum(cast(total_amt AS float)) as revenue,AVG(cast(total_amt as float)) as avg_revenue from Transactions
 where Qty>0 and prod_cat_code 
    in( select top 5 prod_cat_code from Transactions
     where Qty>0
     group by prod_cat_code
     order by sum(cast(total_amt AS float)) desc)
group by prod_subcat_code

   